import {
  Contact,
  Lease,
  LeaseStatus,
  Listing,
  WaitingList,
} from 'onecore-types'

export const mockedParkingSpace: Listing = {
  id: 1,
  rentalObjectCode: '705-808-00-0006',
  address: 'Svarvargatan 4',
  monthlyRent: 698.33,
  districtCaption: 'Malmaberg',
  districtCode: 'MAL',
  blockCaption: 'LINDAREN 2',
  blockCode: '1401',
  objectTypeCaption: 'Carport',
  objectTypeCode: 'CPORT',
  rentalObjectTypeCaption: 'Standard hyresobjektstyp',
  rentalObjectTypeCode: 'STD',
  publishedFrom: new Date('2024-03-26T09:06:56.000Z'),
  publishedTo: new Date('2024-05-04T21:59:59.000Z'),
  vacantFrom: new Date('2023-01-31T23:00:00.000Z'),
  status: 1,
  waitingListType: 'Bilplats (intern)',
}

export const mockedApplicant: Contact = {
  contactCode: 'P12345',
  contactKey: 'ABC',
  address: {
    street: 'Gata',
    number: '2',
    postalCode: '54321',
    city: 'Västerås',
  },
  birthDate: new Date(),
  firstName: 'Foo',
  lastName: 'Bar',
  fullName: 'Foo Bar',
  nationalRegistrationNumber: '1212121212',
  phoneNumbers: [],
  emailAddress: 'test@mimer.nu',
  isTenant: true,
}
export const mockedLeases: Lease[] = [
  {
    leaseId: '123-456-789/0',
    address: {
      street: 'Gatustigen',
      number: '123',
      city: 'Västerås',
      postalCode: '12345',
    },
    approvalDate: undefined,
    contractDate: undefined,
    lastDebitDate: undefined,
    leaseEndDate: undefined,
    leaseNumber: '123',
    leaseStartDate: new Date(),
    noticeDate: undefined,
    noticeGivenBy: 'tenant',
    noticeTimeTenant: '',
    preferredMoveOutDate: undefined,
    rentalProperty: undefined,
    rentalPropertyId: '123-456-789',
    rentInfo: {
      currentRent: {
        currentRent: 123,
        additionalChargeAmount: undefined,
        additionalChargeDescription: undefined,
        rentEndDate: undefined,
        rentStartDate: undefined,
        vat: 0,
      },
      futureRents: undefined,
    },
    status: LeaseStatus.Active,
    tenantContactIds: ['P12345'],
    tenants: undefined,
    terminationDate: undefined,
    type: '',
  },
]

export const mockedWaitingList: WaitingList[] = [
  {
    applicantCaption: 'Foo Bar',
    contactCode: 'P12345',
    contractFromApartment: new Date('2024-02-29T23:00:00.000Z'),
    queuePoints: 45,
    queuePointsSocialConnection: 0,
    waitingListFrom: new Date('2024-01-31T23:00:00.000Z'),
    waitingListTypeCaption: 'Bostad',
  },
  {
    applicantCaption: 'Foo Bar',
    contactCode: 'P12345',
    contractFromApartment: new Date('2024-02-29T23:00:00.000Z'),
    queuePoints: 45,
    queuePointsSocialConnection: 0,
    waitingListFrom: new Date('2024-01-31T23:00:00.000Z'),
    waitingListTypeCaption: 'Bilplats (intern)',
  },
  {
    applicantCaption: 'Foo Bar',
    contactCode: 'P12345',
    contractFromApartment: new Date('2024-02-29T23:00:00.000Z'),
    queuePoints: 45,
    queuePointsSocialConnection: 0,
    waitingListFrom: new Date('2024-01-31T23:00:00.000Z'),
    waitingListTypeCaption: 'Bilplats (extern)',
  },
]
