import {
  Invoice,
  InvoiceTransactionType,
  PaymentStatus,
  WaitingList,
} from 'onecore-types'

const oneDayMs = 24 * 60 * 60 * 1000
const thirtyDaysMs = 30 * 24 * 60 * 60 * 1000
const sixMonthsMs = 182 * 24 * 60 * 60 * 1000

// Non-problematic invoices
export const mockedInvoices: Invoice[] = [
  {
    amount: 123,
    debitStatus: 1,
    paymentStatus: PaymentStatus.Paid,
    fromDate: new Date(),
    toDate: new Date(Date.now() + thirtyDaysMs),
    expirationDate: new Date(Date.now() + thirtyDaysMs),
    invoiceDate: new Date(Date.now() + thirtyDaysMs),
    invoiceId: '123456',
    leaseId: '123-456-789/01',
    transactionType: InvoiceTransactionType.Rent,
    transactionTypeName: 'HYRA',
  },
  {
    amount: 456,
    debitStatus: 1,
    paymentStatus: PaymentStatus.Paid,
    fromDate: new Date(Date.now() - thirtyDaysMs),
    toDate: new Date(Date.now()),
    expirationDate: new Date(Date.now() - thirtyDaysMs),
    invoiceDate: new Date(Date.now() - thirtyDaysMs),
    invoiceId: '3456711',
    leaseId: '123-456-789/01',
    transactionType: InvoiceTransactionType.Rent,
    transactionTypeName: 'HYRA',
  },
  {
    amount: 789,
    debitStatus: 1,
    paymentStatus: PaymentStatus.Unpaid,
    fromDate: new Date(Date.now() - 395 * oneDayMs),
    toDate: new Date(Date.now() - 365 * oneDayMs),
    expirationDate: new Date(Date.now() - 365 * oneDayMs),
    invoiceDate: new Date(Date.now() - 395 * oneDayMs),
    invoiceId: '3456789',
    leaseId: '123-456-789/01',
    transactionType: InvoiceTransactionType.DebtCollection,
    transactionTypeName: 'INKASSOBYRÅ',
  },
  {
    amount: 456,
    debitStatus: 1,
    paymentStatus: PaymentStatus.Unpaid,
    fromDate: new Date(Date.now() - thirtyDaysMs),
    toDate: new Date(Date.now()),
    expirationDate: new Date(Date.now() - thirtyDaysMs),
    invoiceDate: new Date(Date.now() - thirtyDaysMs),
    invoiceId: '3456790',
    leaseId: '123-456-789/01',
    transactionType: InvoiceTransactionType.Rent,
    transactionTypeName: 'HYRA',
  },
]

export const mockedProblematicInvoices: Invoice[] = [
  {
    ...mockedInvoices[0],
    transactionType: InvoiceTransactionType.Reminder,
  },
  {
    ...mockedInvoices[1],
    transactionType: InvoiceTransactionType.DebtCollection,
  },
  {
    ...mockedInvoices[2],
  },
]

export const mockedOldProblematicInvoices: Invoice[] = [
  {
    ...mockedInvoices[0],
    transactionType: InvoiceTransactionType.Reminder,
    expirationDate: new Date(Date.now() - sixMonthsMs - thirtyDaysMs),
  },
  {
    ...mockedInvoices[1],
    transactionType: InvoiceTransactionType.DebtCollection,
    expirationDate: new Date(Date.now() - sixMonthsMs - thirtyDaysMs),
  },
  {
    ...mockedInvoices[2],
  },
]

export const mockedWaitingList: WaitingList[] = [
  {
    applicantCaption: 'Foo Bar',
    contactCode: 'P12345',
    contractFromApartment: new Date('2024-02-29T23:00:00.000Z'),
    queuePoints: 45,
    queuePointsSocialConnection: 0,
    waitingListFrom: new Date('2024-01-31T23:00:00.000Z'),
    waitingListTypeCaption: 'Bostad',
  },
  {
    applicantCaption: 'Foo Bar',
    contactCode: 'P12345',
    contractFromApartment: new Date('2024-02-29T23:00:00.000Z'),
    queuePoints: 45,
    queuePointsSocialConnection: 0,
    waitingListFrom: new Date('2024-01-31T23:00:00.000Z'),
    waitingListTypeCaption: 'Bilplats (intern)',
  },
  {
    applicantCaption: 'Foo Bar',
    contactCode: 'P12345',
    contractFromApartment: new Date('2024-02-29T23:00:00.000Z'),
    queuePoints: 45,
    queuePointsSocialConnection: 0,
    waitingListFrom: new Date('2024-01-31T23:00:00.000Z'),
    waitingListTypeCaption: 'Bilplats (extern)',
  },
]

export const mockedListingWithDetailedApplicants = [
  {
    id: 3005,
    name: 'Sökande Fiktiv',
    contactCode: 'P145241',
    applicationDate: '2024-04-30T14:39:55.1210000',
    applicationType: 'Additional',
    status: 1,
    listingId: 3030,
    queuePoints: 1761,
    address: {
      street: 'Fiktiggatan 1',
      number: '',
      postalCode: '72222',
      city: 'VÄSTERÅS',
    },
    currentHousingContract: {
      leaseId: '306-001-01-0101/07',
      leaseNumber: '07',
      rentalPropertyId: '306-001-01-0101',
      type: 'Bostadskontrakt               ',
      leaseStartDate: '2024-01-01T00:00:00.000Z',
      leaseEndDate: null,
      tenantContactIds: [],
      tenants: [],
      noticeGivenBy: null,
      noticeDate: null,
      noticeTimeTenant: 3,
      preferredMoveOutDate: null,
      terminationDate: null,
      contractDate: '2023-09-27T00:00:00.000Z',
      lastDebitDate: null,
      approvalDate: '2023-09-27T00:00:00.000Z',
      residentalArea: {
        code: 'PET',
        caption: 'Pettersberg',
      },
    },
    upcomingHousingContract: null,
    parkingSpaceContracts: [],
  },
  {
    id: 3006,
    name: 'Testsson Stina',
    contactCode: 'P174965',
    applicationDate: '2024-04-30T14:40:03.5480000',
    applicationType: 'Additional',
    status: 1,
    listingId: 3030,
    queuePoints: 44,
    address: {
      street: 'Testvägen 25',
      number: '',
      postalCode: '12139',
      city: 'JOHANNESHOV',
    },
    currentHousingContract: {
      leaseId: '705-022-04-0201/11',
      leaseNumber: '11',
      rentalPropertyId: '705-022-04-0201',
      type: 'Bostadskontrakt               ',
      leaseStartDate: '2024-03-01T00:00:00.000Z',
      leaseEndDate: null,
      tenantContactIds: [],
      tenants: [],
      noticeGivenBy: null,
      noticeDate: null,
      noticeTimeTenant: 3,
      preferredMoveOutDate: null,
      terminationDate: null,
      contractDate: '2024-02-01T00:00:00.000Z',
      lastDebitDate: null,
      approvalDate: '2024-02-01T00:00:00.000Z',
      residentalArea: {
        code: 'MAL',
        caption: 'Malmaberg',
      },
    },
    upcomingHousingContract: null,
    parkingSpaceContracts: [
      {
        leaseId: '508-713-00-0009/19',
        leaseNumber: '19',
        rentalPropertyId: '508-713-00-0009',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-03-01T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-02-01T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: '2024-02-01T00:00:00.000Z',
        residentalArea: {
          code: 'SKA',
          caption: 'Skallberget',
        },
      },
      {
        leaseId: '216-704-00-0017/02',
        leaseNumber: '02',
        rentalPropertyId: '216-704-00-0017',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-02T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-02T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'SKÄ',
          caption: 'Skälby',
        },
      },
      {
        leaseId: '216-704-00-0027/03',
        leaseNumber: '03',
        rentalPropertyId: '216-704-00-0027',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-02T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-02T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'SKÄ',
          caption: 'Skälby',
        },
      },
      {
        leaseId: '216-704-00-0009/03',
        leaseNumber: '03',
        rentalPropertyId: '216-704-00-0009',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-02T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-02T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'SKÄ',
          caption: 'Skälby',
        },
      },
      {
        leaseId: '216-703-00-0004/03',
        leaseNumber: '03',
        rentalPropertyId: '216-703-00-0004',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-02T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-02T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'SKÄ',
          caption: 'Skälby',
        },
      },
      {
        leaseId: '216-703-00-0009/02',
        leaseNumber: '02',
        rentalPropertyId: '216-703-00-0009',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-02T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-02T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'SKÄ',
          caption: 'Skälby',
        },
      },
      {
        leaseId: '216-703-00-0016/03',
        leaseNumber: '03',
        rentalPropertyId: '216-703-00-0016',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-02T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-02T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'SKÄ',
          caption: 'Skälby',
        },
      },
      {
        leaseId: '216-704-00-0022/02',
        leaseNumber: '02',
        rentalPropertyId: '216-704-00-0022',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-02T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-02T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'SKÄ',
          caption: 'Skälby',
        },
      },
      {
        leaseId: '705-708-00-0004/13',
        leaseNumber: '13',
        rentalPropertyId: '705-708-00-0004',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-03T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-03T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'MAL',
          caption: 'Malmaberg',
        },
      },
      {
        leaseId: '216-703-00-0007/03',
        leaseNumber: '03',
        rentalPropertyId: '216-703-00-0007',
        type: 'P-Platskontrakt               ',
        leaseStartDate: '2024-04-04T00:00:00.000Z',
        leaseEndDate: null,
        tenantContactIds: [],
        tenants: [],
        noticeGivenBy: null,
        noticeDate: null,
        noticeTimeTenant: 3,
        preferredMoveOutDate: null,
        terminationDate: null,
        contractDate: '2024-04-04T00:00:00.000Z',
        lastDebitDate: null,
        approvalDate: null,
        residentalArea: {
          code: 'SKÄ',
          caption: 'Skälby',
        },
      },
    ],
  },
]
