export const columnIndexes: Record<string, number> = {
  rentArticle: 1,
  invoiceRowText: 2,
  totalAmount: 3,
  invoiceDate: 4,
  deferDate: 5,
  numberOfArticles: 6,
  pricePerArticle: 7,
  deduction: 8,
  accountingDate: 9,
  debitState: 10,
  unit: 11,
  invoiceAmount: 12,
  invoiceType: 13,
  company: 14,
  companyName: 15,
  dueDate: 16,
  contactCode: 17,
  tenantName: 18,
  amount: 19,
  vat: 20,
  paymentStatus: 21,
  remainingPayment: 22,
  finalPaymentDate: 23,
  transactionType: 24,
  voucherId: 25,
  contractCode: 26,
  invoiceNumber: 27,
}

export const columnNames: string[] = [
  'rentArticle',
  'invoiceRowText',
  'totalAmount',
  'invoiceDate',
  'deferDate',
  'numberOfArticles',
  'pricePerArticle',
  'deduction',
  'accountingDate',
  'debitState',
  'unit',
  'invoiceAmount',
  'invoiceType',
  'company',
  'companyName',
  'dueDate',
  'contactCode',
  'tenantName',
  'amount',
  'vat',
  'paymentStatus',
  'remainingPayment',
  'finalPaymentDate',
  'transactionType',
  'voucherId',
  'contractCode',
  'invoiceNumber',
]
/*export const columnIndexes: Record<string, number> = {
  contractCode: 1,
  contactCode: 2,
  tenantName: 3,
  contractType: 4,
  contractFromDate: 5,
  invoiceFromDate: 6,
  invoiceToDate: 7,
  rentArticle: 8,
  invoiceRowText: 9,
  contractArea: 10,
  sumContractArea: 11,
  rentalObjectCode: 12,
  rentalObjectName: 13,
  amount: 14,
  vat: 15,
  totalAmount: 16,
  account: 17,
  costCode: 18,
  projectCode: 19,
  freeCode: 20,
  sumRow: 21,
}

export const columnNames: string[] = [
  'contractCode',
  'contactCode',
  'tenantName',
  'contractType',
  'contractFromDate',
  'invoiceFromDate',
  'invoiceToDate',
  'rentArticle',
  'invoiceRowText',
  'contractArea',
  'sumContractArea',
  'rentalObjectCode',
  'rentalObjectName',
  'amount',
  'vat',
  'totalAmount',
  'account',
  'costCode',
  'projectCode',
  'freeCode',
  'sumRow',
]*/

export type InvoiceDataRow = Record<string, string | number>
