import { Factory } from 'fishery'
import { components } from '../../src/adapters/property-base-adapter/generated/api-types'

export const PropertyDetailsFactory = Factory.define<
  components['schemas']['PropertyDetails']
>(({ sequence }) => ({
  id: `property_${sequence}`,
  propertyObjectId: `object_${sequence}`,
  marketAreaId: `market_${sequence}`,
  districtId: `district_${sequence}`,
  propertyDesignationId: `designation_${sequence}`,
  valueAreaId: null,
  code: `code_${sequence}`,
  designation: `Designation ${sequence}`,
  municipality: 'Västerås',
  tract: `Tract ${sequence}`,
  block: `Block ${sequence}`,
  sector: null,
  propertyIndexNumber: null,
  congregation: 'Västerås',
  builtStatus: 0,
  separateAssessmentUnit: 0,
  consolidationNumber: `consolidation_${sequence}`,
  ownershipType: 'OwnershipType',
  registrationDate: null,
  acquisitionDate: null,
  isLeasehold: 0,
  leaseholdTerminationDate: null,
  area: null,
  purpose: null,
  buildingType: null,
  propertyTaxNumber: null,
  mainPartAssessedValue: 0,
  includeInAssessedValue: 0,
  grading: 0,
  deleteMark: 0,
  fromDate: new Date().toISOString(),
  toDate: new Date().toISOString(),
  timestamp: new Date().toISOString(),
  propertyObject: {
    id: `object_${sequence}`,
    deleteMark: 0,
    timestamp: new Date().toISOString(),
    objectTypeId: `type_${sequence}`,
    barcode: null,
    barcodeType: 0,
    condition: 0,
    conditionInspectionDate: null,
    vatAdjustmentPrinciple: 0,
    energyClass: 0,
    energyRegistered: null,
    energyReceived: null,
    energyIndex: null,
    heatingNature: 0,
  },
}))
